// This code generated by Zoop\Shard\Dojo
define([
    'dojo/_base/declare',    
    'havok/mvc/BaseModel'
],
function(
    declare,    
    BaseModel
){
    // Will return a model for Zoop\Shard\Test\Dojo\TestAsset\Document\Simple

    return declare(
        [            
            BaseModel        
        ],
        {
            _fields: [
            	"id",
            	"name",
            	"country",
            	"camelCaseField",
            	"_className"
            ],
            
            _className: 'Zoop\\Shard\\Test\\Dojo\\TestAsset\\Document\\Simple'
        }
    );
});
