// This code generated by Zoop\Shard\Dojo
define([
    'dojo/_base/declare',    
    'havok/form/ValidationControlGroup',
    'shard/simple/MultiFieldValidator',
    'Zoop/Shard/Test/Dojo/TestAsset/Document/Simple/Id/Input',
    'shard/simple/NameInput',
    'Zoop/Shard/Test/Dojo/TestAsset/Document/Simple/Country/Input',
    'Zoop/Shard/Test/Dojo/TestAsset/Document/Simple/CamelCaseField/Input'
],
function(
    declare,    
    ValidationControlGroup,
    MultiFieldValidator,
    IdInput,
    NameInput,
    CountryInput,
    CamelCaseFieldInput
){
    // Will return a form for Zoop\Shard\Test\Dojo\TestAsset\Document\Simple

    return declare(
        [            
            ValidationControlGroup        
        ],
        {
            validator: new MultiFieldValidator,
            
            inputs: [
            	new IdInput,
            	new NameInput,
            	new CountryInput,
            	new CamelCaseFieldInput
            ]
        }
    );
});
