// This code generated by Zoop\Shard\Dojo
define([
    'dojo/_base/declare',    
    'havok/validator/Model',
    'shard/simple/MultiFieldValidator',
    'shard/simple/NameValidator',
    'Zoop/Shard/Test/Dojo/TestAsset/Document/Simple/Country/Validator'
],
function(
    declare,    
    Model,
    MultiFieldValidator,
    NameValidator,
    CountryValidator
){
    // Will return a validator to validate a complete model for Zoop\Shard\Test\Dojo\TestAsset\Document\Simple

    return declare(
        [            
            Model        
        ],
        {
            validators: [
            	new MultiFieldValidator,
            	new NameValidator,
            	new CountryValidator
            ]
        }
    );
});
