// This code generated by Zoop\Shard\Dojo
define([
    'dojo/_base/declare',    
    'mystique/chain',
    'Zoop/Mystique/Chain'
],
function(
    declare,    
    chain,
    Chain
){
    // Will return a multi field validator

    return declare(
        [            
            chain        
        ],
        {
            validators: [
            	new Chain({
            		
                "validators": [
            			
                    {
            				
                        "class": "Zoop\/Shard\/Test\/ClassValidator1",
            				
                        "options": [
            					
            
                        
            				]				
                    
            			},
            			
                    {
            				
                        "class": "Zoop\/Shard\/Test\/ClassValidator2",
            				
                        "options": {
            					
                            "option1": "a",
            					
                            "option2": "b"
                        
            				}				
                    
            			}			
                
            		]		
            
            	}	)
            ]
        }
    );
});
