// This code generated by Zoop\Shard\Dojo
define([
    'dojo/_base/declare',    
    'mystique/chain',
    'Zoop/Mystique/Chain'
],
function(
    declare,    
    chain,
    Chain
){
    // Will return a validator that can be used to check
    // the name field

    return declare(
        [            
            chain        
        ],
        {
            field: 'name',
            
            validators: [
            	new Chain({
            		"validators":[
            			{
            				"class":"Zoop\\Mystique\\Required"
            			},
            			{
            				"class":"Zoop\/Shard\/Test\/NameValidator1",
            				"options":[
            
            				]
            			},
            			{
            				"class":"Zoop\/Shard\/Test\/NameValidator2",
            				"options":{
            					"option1":"b",
            					"option2":"b"
            				}
            			}
            		]
            	}	)
            ]
        }
    );
});
