// This code generated by Zoop\Shard\Dojo
define([
    'dojo/_base/declare',    
    'havok/mvc/JsonRest',
    'shard/simple'
],
function(
    declare,    
    JsonRest,
    simple
){
    // Will return create a dojo JsonRest store for Zoop\Shard\Test\Dojo\TestAsset\Document\Simple

    return declare(
        [            
            JsonRest        
        ],
        {
            name: 'Simple',
            
            idField: 'id',
            
            target: 'Simple',
            
            model: simple
        }
    );
});
